<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'iso_alpha_2' => 'AF', 'iso_alpha_3' => 'AFG'],
            ['name' => 'Åland Islands', 'iso_alpha_2' => 'AX', 'iso_alpha_3' => 'ALA'],
            ['name' => 'Albania', 'iso_alpha_2' => 'AL', 'iso_alpha_3' => 'ALB'],
            ['name' => 'Algeria', 'iso_alpha_2' => 'DZ', 'iso_alpha_3' => 'DZA'],
            ['name' => 'American Samoa', 'iso_alpha_2' => 'AS', 'iso_alpha_3' => 'ASM'],
            ['name' => 'Andorra', 'iso_alpha_2' => 'AD', 'iso_alpha_3' => 'AND'],
            ['name' => 'Angola', 'iso_alpha_2' => 'AO', 'iso_alpha_3' => 'AGO'],
            ['name' => 'Anguilla', 'iso_alpha_2' => 'AI', 'iso_alpha_3' => 'AIA'],
            ['name' => 'Antarctica', 'iso_alpha_2' => 'AQ', 'iso_alpha_3' => 'ATA'],
            ['name' => 'Antigua and Barbuda', 'iso_alpha_2' => 'AG', 'iso_alpha_3' => 'ATG'],
            ['name' => 'Argentina', 'iso_alpha_2' => 'AR', 'iso_alpha_3' => 'ARG'],
            ['name' => 'Armenia', 'iso_alpha_2' => 'AM', 'iso_alpha_3' => 'ARM'],
            ['name' => 'Aruba', 'iso_alpha_2' => 'AW', 'iso_alpha_3' => 'ABW'],
            ['name' => 'Australia', 'iso_alpha_2' => 'AU', 'iso_alpha_3' => 'AUS'],
            ['name' => 'Austria', 'iso_alpha_2' => 'AT', 'iso_alpha_3' => 'AUT'],
            ['name' => 'Azerbaijan', 'iso_alpha_2' => 'AZ', 'iso_alpha_3' => 'AZE'],
            ['name' => 'Bahamas', 'iso_alpha_2' => 'BS', 'iso_alpha_3' => 'BHS'],
            ['name' => 'Bahrain', 'iso_alpha_2' => 'BH', 'iso_alpha_3' => 'BHR'],
            ['name' => 'Bangladesh', 'iso_alpha_2' => 'BD', 'iso_alpha_3' => 'BGD'],
            ['name' => 'Barbados', 'iso_alpha_2' => 'BB', 'iso_alpha_3' => 'BRB'],

            ['name' => 'Belarus', 'iso_alpha_2' => 'BY', 'iso_alpha_3' => 'BLR'],
            ['name' => 'Belgium', 'iso_alpha_2' => 'BE', 'iso_alpha_3' => 'BEL'],
            ['name' => 'Belize', 'iso_alpha_2' => 'BZ', 'iso_alpha_3' => 'BLZ'],
            ['name' => 'Benin', 'iso_alpha_2' => 'BJ', 'iso_alpha_3' => 'BEN'],
            ['name' => 'Bermuda', 'iso_alpha_2' => 'BM', 'iso_alpha_3' => 'BMU'],
            ['name' => 'Bhutan', 'iso_alpha_2' => 'BT', 'iso_alpha_3' => 'BTN'],
            ['name' => 'Bolivia, Plurinational State of', 'iso_alpha_2' => 'BO', 'iso_alpha_3' => 'BOL'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'iso_alpha_2' => 'BQ', 'iso_alpha_3' => 'BES'],
            ['name' => 'Bosnia and Herzegovina', 'iso_alpha_2' => 'BA', 'iso_alpha_3' => 'BIH'],
            ['name' => 'Botswana', 'iso_alpha_2' => 'BW', 'iso_alpha_3' => 'BWA'],
            ['name' => 'Bouvet Island', 'iso_alpha_2' => 'BV', 'iso_alpha_3' => 'BVT'],
            ['name' => 'Brazil', 'iso_alpha_2' => 'BR', 'iso_alpha_3' => 'BRA'],
            ['name' => 'British Indian Ocean Territory', 'iso_alpha_2' => 'IO', 'iso_alpha_3' => 'IOT'],
            ['name' => 'Brunei Darussalam', 'iso_alpha_2' => 'BN', 'iso_alpha_3' => 'BRN'],
            ['name' => 'Bulgaria', 'iso_alpha_2' => 'BG', 'iso_alpha_3' => 'BGR'],
            ['name' => 'Burkina Faso', 'iso_alpha_2' => 'BF', 'iso_alpha_3' => 'BFA'],
            ['name' => 'Burundi', 'iso_alpha_2' => 'BI', 'iso_alpha_3' => 'BDI'],
            ['name' => 'Cabo Verde', 'iso_alpha_2' => 'CV', 'iso_alpha_3' => 'CPV'],
            ['name' => 'Cambodia', 'iso_alpha_2' => 'KH', 'iso_alpha_3' => 'KHM'],
            ['name' => 'Cameroon', 'iso_alpha_2' => 'CM', 'iso_alpha_3' => 'CMR'],

            ['name' => 'Canada', 'iso_alpha_2' => 'CA', 'iso_alpha_3' => 'CAN'],
            ['name' => 'Cayman Islands', 'iso_alpha_2' => 'KY', 'iso_alpha_3' => 'CYM'],
            ['name' => 'Central African Republic', 'iso_alpha_2' => 'CF', 'iso_alpha_3' => 'CAF'],
            ['name' => 'Chad', 'iso_alpha_2' => 'TD', 'iso_alpha_3' => 'TCD'],
            ['name' => 'Chile', 'iso_alpha_2' => 'CL', 'iso_alpha_3' => 'CHL'],
            ['name' => 'China', 'iso_alpha_2' => 'CN', 'iso_alpha_3' => 'CHN'],
            ['name' => 'Christmas Island', 'iso_alpha_2' => 'CX', 'iso_alpha_3' => 'CXR'],
            ['name' => 'Cocos (Keeling) Islands', 'iso_alpha_2' => 'CC', 'iso_alpha_3' => 'CCK'],
            ['name' => 'Colombia', 'iso_alpha_2' => 'CO', 'iso_alpha_3' => 'COL'],
            ['name' => 'Comoros', 'iso_alpha_2' => 'KM', 'iso_alpha_3' => 'COM'],
            ['name' => 'Congo', 'iso_alpha_2' => 'CG', 'iso_alpha_3' => 'COG'],
            ['name' => 'Congo, the Democratic Republic of the', 'iso_alpha_2' => 'CD', 'iso_alpha_3' => 'COD'],
            ['name' => 'Cook Islands', 'iso_alpha_2' => 'CK', 'iso_alpha_3' => 'COK'],
            ['name' => 'Costa Rica', 'iso_alpha_2' => 'CR', 'iso_alpha_3' => 'CRI'],
            ['name' => 'Côte d\'Ivoire', 'iso_alpha_2' => 'CI', 'iso_alpha_3' => 'CIV'],
            ['name' => 'Croatia', 'iso_alpha_2' => 'HR', 'iso_alpha_3' => 'HRV'],
            ['name' => 'Cuba', 'iso_alpha_2' => 'CU', 'iso_alpha_3' => 'CUB'],
            ['name' => 'Curaçao', 'iso_alpha_2' => 'CW', 'iso_alpha_3' => 'CUW'],
            ['name' => 'Cyprus', 'iso_alpha_2' => 'CY', 'iso_alpha_3' => 'CYP'],
            ['name' => 'Czech Republic', 'iso_alpha_2' => 'CZ', 'iso_alpha_3' => 'CZE'],

            ['name' => 'Denmark', 'iso_alpha_2' => 'DK', 'iso_alpha_3' => 'DNK'],
            ['name' => 'Djibouti', 'iso_alpha_2' => 'DJ', 'iso_alpha_3' => 'DJI'],
            ['name' => 'Dominica', 'iso_alpha_2' => 'DM', 'iso_alpha_3' => 'DMA'],
            ['name' => 'Dominican Republic', 'iso_alpha_2' => 'DO', 'iso_alpha_3' => 'DOM'],
            ['name' => 'Ecuador', 'iso_alpha_2' => 'EC', 'iso_alpha_3' => 'ECU'],
            ['name' => 'Egypt', 'iso_alpha_2' => 'EG', 'iso_alpha_3' => 'EGY'],
            ['name' => 'El Salvador', 'iso_alpha_2' => 'SV', 'iso_alpha_3' => 'SLV'],
            ['name' => 'Equatorial Guinea', 'iso_alpha_2' => 'GQ', 'iso_alpha_3' => 'GNQ'],
            ['name' => 'Eritrea', 'iso_alpha_2' => 'ER', 'iso_alpha_3' => 'ERI'],
            ['name' => 'Estonia', 'iso_alpha_2' => 'EE', 'iso_alpha_3' => 'EST'],
            ['name' => 'Ethiopia', 'iso_alpha_2' => 'ET', 'iso_alpha_3' => 'ETH'],
            ['name' => 'Falkland Islands (Malvinas)', 'iso_alpha_2' => 'FK', 'iso_alpha_3' => 'FLK'],
            ['name' => 'Faroe Islands', 'iso_alpha_2' => 'FO', 'iso_alpha_3' => 'FRO'],
            ['name' => 'Fiji', 'iso_alpha_2' => 'FJ', 'iso_alpha_3' => 'FJI'],
            ['name' => 'Finland', 'iso_alpha_2' => 'FI', 'iso_alpha_3' => 'FIN'],
            ['name' => 'France', 'iso_alpha_2' => 'FR', 'iso_alpha_3' => 'FRA'],
            ['name' => 'French Guiana', 'iso_alpha_2' => 'GF', 'iso_alpha_3' => 'GUF'],
            ['name' => 'French Polynesia', 'iso_alpha_2' => 'PF', 'iso_alpha_3' => 'PYF'],
            ['name' => 'French Southern Territories', 'iso_alpha_2' => 'TF', 'iso_alpha_3' => 'ATF'],
            ['name' => 'Gabon', 'iso_alpha_2' => 'GA', 'iso_alpha_3' => 'GAB'],

            ['name' => 'Gambia', 'iso_alpha_2' => 'GM', 'iso_alpha_3' => 'GMB'],
            ['name' => 'Georgia', 'iso_alpha_2' => 'GE', 'iso_alpha_3' => 'GEO'],
            ['name' => 'Germany', 'iso_alpha_2' => 'DE', 'iso_alpha_3' => 'DEU'],
            ['name' => 'Ghana', 'iso_alpha_2' => 'GH', 'iso_alpha_3' => 'GHA'],
            ['name' => 'Gibraltar', 'iso_alpha_2' => 'GI', 'iso_alpha_3' => 'GIB'],
            ['name' => 'Greece', 'iso_alpha_2' => 'GR', 'iso_alpha_3' => 'GRC'],
            ['name' => 'Greenland', 'iso_alpha_2' => 'GL', 'iso_alpha_3' => 'GRL'],
            ['name' => 'Grenada', 'iso_alpha_2' => 'GD', 'iso_alpha_3' => 'GRD'],
            ['name' => 'Guadeloupe', 'iso_alpha_2' => 'GP', 'iso_alpha_3' => 'GLP'],
            ['name' => 'Guam', 'iso_alpha_2' => 'GU', 'iso_alpha_3' => 'GUM'],
            ['name' => 'Guatemala', 'iso_alpha_2' => 'GT', 'iso_alpha_3' => 'GTM'],
            ['name' => 'Guernsey', 'iso_alpha_2' => 'GG', 'iso_alpha_3' => 'GGY'],
            ['name' => 'Guinea', 'iso_alpha_2' => 'GN', 'iso_alpha_3' => 'GIN'],
            ['name' => 'Guinea-Bissau', 'iso_alpha_2' => 'GW', 'iso_alpha_3' => 'GNB'],
            ['name' => 'Guyana', 'iso_alpha_2' => 'GY', 'iso_alpha_3' => 'GUY'],
            ['name' => 'Haiti', 'iso_alpha_2' => 'HT', 'iso_alpha_3' => 'HTI'],
            ['name' => 'Heard Island and McDonald Mcdonald Islands', 'iso_alpha_2' => 'HM', 'iso_alpha_3' => 'HMD'],
            ['name' => 'Holy See (Vatican City State)', 'iso_alpha_2' => 'VA', 'iso_alpha_3' => 'VAT'],
            ['name' => 'Honduras', 'iso_alpha_2' => 'HN', 'iso_alpha_3' => 'HND'],
            ['name' => 'Hong Kong', 'iso_alpha_2' => 'HK', 'iso_alpha_3' => 'HKG'],

            ['name' => 'Hungary', 'iso_alpha_2' => 'HU', 'iso_alpha_3' => 'HUN'],
            ['name' => 'Iceland', 'iso_alpha_2' => 'IS', 'iso_alpha_3' => 'ISL'],
            ['name' => 'India', 'iso_alpha_2' => 'IN', 'iso_alpha_3' => 'IND'],
            ['name' => 'Indonesia', 'iso_alpha_2' => 'ID', 'iso_alpha_3' => 'IDN'],
            ['name' => 'Iran, Islamic Republic of', 'iso_alpha_2' => 'IR', 'iso_alpha_3' => 'IRN'],
            ['name' => 'Iraq', 'iso_alpha_2' => 'IQ', 'iso_alpha_3' => 'IRQ'],
            ['name' => 'Ireland', 'iso_alpha_2' => 'IE', 'iso_alpha_3' => 'IRL'],
            ['name' => 'Isle of Man', 'iso_alpha_2' => 'IM', 'iso_alpha_3' => 'IMN'],
            ['name' => 'Israel', 'iso_alpha_2' => 'IL', 'iso_alpha_3' => 'ISR'],
            ['name' => 'Italy', 'iso_alpha_2' => 'IT', 'iso_alpha_3' => 'ITA'],
            ['name' => 'Jamaica', 'iso_alpha_2' => 'JM', 'iso_alpha_3' => 'JAM'],
            ['name' => 'Japan', 'iso_alpha_2' => 'JP', 'iso_alpha_3' => 'JPN'],
            ['name' => 'Jersey', 'iso_alpha_2' => 'JE', 'iso_alpha_3' => 'JEY'],
            ['name' => 'Jordan', 'iso_alpha_2' => 'JO', 'iso_alpha_3' => 'JOR'],
            ['name' => 'Kazakhstan', 'iso_alpha_2' => 'KZ', 'iso_alpha_3' => 'KAZ'],
            ['name' => 'Kenya', 'iso_alpha_2' => 'KE', 'iso_alpha_3' => 'KEN'],
            ['name' => 'Kiribati', 'iso_alpha_2' => 'KI', 'iso_alpha_3' => 'KIR'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'iso_alpha_2' => 'KP', 'iso_alpha_3' => 'PRK'],
            ['name' => 'Korea, Republic of', 'iso_alpha_2' => 'KR', 'iso_alpha_3' => 'KOR'],
            ['name' => 'Kuwait', 'iso_alpha_2' => 'KW', 'iso_alpha_3' => 'KWT'],

            ['name' => 'Kyrgyzstan', 'iso_alpha_2' => 'KG', 'iso_alpha_3' => 'KGZ'],
            ['name' => 'Lao People\'s Democratic Republic', 'iso_alpha_2' => 'LA', 'iso_alpha_3' => 'LAO'],
            ['name' => 'Latvia', 'iso_alpha_2' => 'LV', 'iso_alpha_3' => 'LVA'],
            ['name' => 'Lebanon', 'iso_alpha_2' => 'LB', 'iso_alpha_3' => 'LBN'],
            ['name' => 'Lesotho', 'iso_alpha_2' => 'LS', 'iso_alpha_3' => 'LSO'],
            ['name' => 'Liberia', 'iso_alpha_2' => 'LR', 'iso_alpha_3' => 'LBR'],
            ['name' => 'Libya', 'iso_alpha_2' => 'LY', 'iso_alpha_3' => 'LBY'],
            ['name' => 'Liechtenstein', 'iso_alpha_2' => 'LI', 'iso_alpha_3' => 'LIE'],
            ['name' => 'Lithuania', 'iso_alpha_2' => 'LT', 'iso_alpha_3' => 'LTU'],
            ['name' => 'Luxembourg', 'iso_alpha_2' => 'LU', 'iso_alpha_3' => 'LUX'],
            ['name' => 'Macao', 'iso_alpha_2' => 'MO', 'iso_alpha_3' => 'MAC'],
            ['name' => 'Macedonia, the Former Yugoslav Republic of', 'iso_alpha_2' => 'MK', 'iso_alpha_3' => 'MKD'],
            ['name' => 'Madagascar', 'iso_alpha_2' => 'MG', 'iso_alpha_3' => 'MDG'],
            ['name' => 'Malawi', 'iso_alpha_2' => 'MW', 'iso_alpha_3' => 'MWI'],
            ['name' => 'Malaysia', 'iso_alpha_2' => 'MY', 'iso_alpha_3' => 'MYS'],
            ['name' => 'Maldives', 'iso_alpha_2' => 'MV', 'iso_alpha_3' => 'MDV'],
            ['name' => 'Mali', 'iso_alpha_2' => 'ML', 'iso_alpha_3' => 'MLI'],
            ['name' => 'Malta', 'iso_alpha_2' => 'MT', 'iso_alpha_3' => 'MLT'],
            ['name' => 'Marshall Islands', 'iso_alpha_2' => 'MH', 'iso_alpha_3' => 'MHL'],
            ['name' => 'Martinique', 'iso_alpha_2' => 'MQ', 'iso_alpha_3' => 'MTQ'],

            ['name' => 'Mauritania', 'iso_alpha_2' => 'MR', 'iso_alpha_3' => 'MRT'],
            ['name' => 'Mauritius', 'iso_alpha_2' => 'MU', 'iso_alpha_3' => 'MUS'],
            ['name' => 'Mayotte', 'iso_alpha_2' => 'YT', 'iso_alpha_3' => 'MYT'],
            ['name' => 'Mexico', 'iso_alpha_2' => 'MX', 'iso_alpha_3' => 'MEX'],
            ['name' => 'Micronesia, Federated States of', 'iso_alpha_2' => 'FM', 'iso_alpha_3' => 'FSM'],
            ['name' => 'Moldova, Republic of', 'iso_alpha_2' => 'MD', 'iso_alpha_3' => 'MDA'],
            ['name' => 'Monaco', 'iso_alpha_2' => 'MC', 'iso_alpha_3' => 'MCO'],
            ['name' => 'Mongolia', 'iso_alpha_2' => 'MN', 'iso_alpha_3' => 'MNG'],
            ['name' => 'Montenegro', 'iso_alpha_2' => 'ME', 'iso_alpha_3' => 'MNE'],
            ['name' => 'Montserrat', 'iso_alpha_2' => 'MS', 'iso_alpha_3' => 'MSR'],
            ['name' => 'Morocco', 'iso_alpha_2' => 'MA', 'iso_alpha_3' => 'MAR'],
            ['name' => 'Mozambique', 'iso_alpha_2' => 'MZ', 'iso_alpha_3' => 'MOZ'],
            ['name' => 'Myanmar', 'iso_alpha_2' => 'MM', 'iso_alpha_3' => 'MMR'],
            ['name' => 'Namibia', 'iso_alpha_2' => 'NA', 'iso_alpha_3' => 'NAM'],
            ['name' => 'Nauru', 'iso_alpha_2' => 'NR', 'iso_alpha_3' => 'NRU'],
            ['name' => 'Nepal', 'iso_alpha_2' => 'NP', 'iso_alpha_3' => 'NPL'],
            ['name' => 'Netherlands', 'iso_alpha_2' => 'NL', 'iso_alpha_3' => 'NLD'],
            ['name' => 'New Caledonia', 'iso_alpha_2' => 'NC', 'iso_alpha_3' => 'NCL'],
            ['name' => 'New Zealand', 'iso_alpha_2' => 'NZ', 'iso_alpha_3' => 'NZL'],
            ['name' => 'Nicaragua', 'iso_alpha_2' => 'NI', 'iso_alpha_3' => 'NIC'],

            ['name' => 'Niger', 'iso_alpha_2' => 'NE', 'iso_alpha_3' => 'NER'],
            ['name' => 'Nigeria', 'iso_alpha_2' => 'NG', 'iso_alpha_3' => 'NGA'],
            ['name' => 'Niue', 'iso_alpha_2' => 'NU', 'iso_alpha_3' => 'NIU'],
            ['name' => 'Norfolk Island', 'iso_alpha_2' => 'NF', 'iso_alpha_3' => 'NFK'],
            ['name' => 'Northern Mariana Islands', 'iso_alpha_2' => 'MP', 'iso_alpha_3' => 'MNP'],
            ['name' => 'Norway', 'iso_alpha_2' => 'NO', 'iso_alpha_3' => 'NOR'],
            ['name' => 'Oman', 'iso_alpha_2' => 'OM', 'iso_alpha_3' => 'OMN'],
            ['name' => 'Pakistan', 'iso_alpha_2' => 'PK', 'iso_alpha_3' => 'PAK'],
            ['name' => 'Palau', 'iso_alpha_2' => 'PW', 'iso_alpha_3' => 'PLW'],
            ['name' => 'Palestine, State of', 'iso_alpha_2' => 'PS', 'iso_alpha_3' => 'PSE'],
            ['name' => 'Panama', 'iso_alpha_2' => 'PA', 'iso_alpha_3' => 'PAN'],
            ['name' => 'Papua New Guinea', 'iso_alpha_2' => 'PG', 'iso_alpha_3' => 'PNG'],
            ['name' => 'Paraguay', 'iso_alpha_2' => 'PY', 'iso_alpha_3' => 'PRY'],
            ['name' => 'Peru', 'iso_alpha_2' => 'PE', 'iso_alpha_3' => 'PER'],
            ['name' => 'Philippines', 'iso_alpha_2' => 'PH', 'iso_alpha_3' => 'PHL'],
            ['name' => 'Pitcairn', 'iso_alpha_2' => 'PN', 'iso_alpha_3' => 'PCN'],
            ['name' => 'Poland', 'iso_alpha_2' => 'PL', 'iso_alpha_3' => 'POL'],
            ['name' => 'Portugal', 'iso_alpha_2' => 'PT', 'iso_alpha_3' => 'PRT'],
            ['name' => 'Puerto Rico', 'iso_alpha_2' => 'PR', 'iso_alpha_3' => 'PRI'],
            ['name' => 'Qatar', 'iso_alpha_2' => 'QA', 'iso_alpha_3' => 'QAT'],

            ['name' => 'Réunion', 'iso_alpha_2' => 'RE', 'iso_alpha_3' => 'REU'],
            ['name' => 'Romania', 'iso_alpha_2' => 'RO', 'iso_alpha_3' => 'ROU'],
            ['name' => 'Russian Federation', 'iso_alpha_2' => 'RU', 'iso_alpha_3' => 'RUS'],
            ['name' => 'Rwanda', 'iso_alpha_2' => 'RW', 'iso_alpha_3' => 'RWA'],
            ['name' => 'Saint Barthélemy', 'iso_alpha_2' => 'BL', 'iso_alpha_3' => 'BLM'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'iso_alpha_2' => 'SH', 'iso_alpha_3' => 'SHN'],
            ['name' => 'Saint Kitts and Nevis', 'iso_alpha_2' => 'KN', 'iso_alpha_3' => 'KNA'],
            ['name' => 'Saint Lucia', 'iso_alpha_2' => 'LC', 'iso_alpha_3' => 'LCA'],
            ['name' => 'Saint Martin (French part)', 'iso_alpha_2' => 'MF', 'iso_alpha_3' => 'MAF'],
            ['name' => 'Saint Pierre and Miquelon', 'iso_alpha_2' => 'PM', 'iso_alpha_3' => 'SPM'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_alpha_2' => 'VC', 'iso_alpha_3' => 'VCT'],
            ['name' => 'Samoa', 'iso_alpha_2' => 'WS', 'iso_alpha_3' => 'WSM'],
            ['name' => 'San Marino', 'iso_alpha_2' => 'SM', 'iso_alpha_3' => 'SMR'],
            ['name' => 'Sao Tome and Principe', 'iso_alpha_2' => 'ST', 'iso_alpha_3' => 'STP'],
            ['name' => 'Saudi Arabia', 'iso_alpha_2' => 'SA', 'iso_alpha_3' => 'SAU'],
            ['name' => 'Senegal', 'iso_alpha_2' => 'SN', 'iso_alpha_3' => 'SEN'],
            ['name' => 'Serbia', 'iso_alpha_2' => 'RS', 'iso_alpha_3' => 'SRB'],
            ['name' => 'Seychelles', 'iso_alpha_2' => 'SC', 'iso_alpha_3' => 'SYC'],
            ['name' => 'Sierra Leone', 'iso_alpha_2' => 'SL', 'iso_alpha_3' => 'SLE'],
            ['name' => 'Singapore', 'iso_alpha_2' => 'SG', 'iso_alpha_3' => 'SGP'],

            ['name' => 'Sint Maarten (Dutch part)', 'iso_alpha_2' => 'SX', 'iso_alpha_3' => '----'],
            ['name' => 'Slovakia', 'iso_alpha_2' => 'SK', 'iso_alpha_3' => 'SVK'],
            ['name' => 'Slovenia', 'iso_alpha_2' => 'SI', 'iso_alpha_3' => 'SVN'],
            ['name' => 'Solomon Islands', 'iso_alpha_2' => 'SB', 'iso_alpha_3' => 'SLB'],
            ['name' => 'Somalia', 'iso_alpha_2' => 'SO', 'iso_alpha_3' => 'SOM'],
            ['name' => 'South Africa', 'iso_alpha_2' => 'ZA', 'iso_alpha_3' => 'ZAF'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'iso_alpha_2' => 'GS', 'iso_alpha_3' => 'SGS'],
            ['name' => 'South Sudan', 'iso_alpha_2' => 'SS', 'iso_alpha_3' => '----'],
            ['name' => 'Spain', 'iso_alpha_2' => 'ES', 'iso_alpha_3' => 'ESP'],
            ['name' => 'Sri Lanka', 'iso_alpha_2' => 'LK', 'iso_alpha_3' => 'LKA'],
            ['name' => 'Sudan', 'iso_alpha_2' => 'SD', 'iso_alpha_3' => 'SDN'],
            ['name' => 'Suriname', 'iso_alpha_2' => 'SR', 'iso_alpha_3' => 'SUR'],
            ['name' => 'Svalbard and Jan Mayen', 'iso_alpha_2' => 'SJ', 'iso_alpha_3' => 'SJM'],
            ['name' => 'Swaziland', 'iso_alpha_2' => 'SZ', 'iso_alpha_3' => 'SWZ'],
            ['name' => 'Sweden', 'iso_alpha_2' => 'SE', 'iso_alpha_3' => 'SWE'],
            ['name' => 'Switzerland', 'iso_alpha_2' => 'CH', 'iso_alpha_3' => 'CHE'],
            ['name' => 'Syrian Arab Republic', 'iso_alpha_2' => 'SY', 'iso_alpha_3' => 'SYR'],
            ['name' => 'Taiwan', 'iso_alpha_2' => 'TW', 'iso_alpha_3' => 'TWN'],
            ['name' => 'Tajikistan', 'iso_alpha_2' => 'TJ', 'iso_alpha_3' => 'TJK'],
            ['name' => 'Tanzania, United Republic of', 'iso_alpha_2' => 'TZ', 'iso_alpha_3' => 'TZA'],

            ['name' => 'Thailand', 'iso_alpha_2' => 'TH', 'iso_alpha_3' => 'THA'],
            ['name' => 'Timor-Leste', 'iso_alpha_2' => 'TL', 'iso_alpha_3' => 'TLS'],
            ['name' => 'Togo', 'iso_alpha_2' => 'TG', 'iso_alpha_3' => 'TGO'],
            ['name' => 'Tokelau', 'iso_alpha_2' => 'TK', 'iso_alpha_3' => 'TKL'],
            ['name' => 'Tonga', 'iso_alpha_2' => 'TO', 'iso_alpha_3' => 'TON'],
            ['name' => 'Trinidad and Tobago', 'iso_alpha_2' => 'TT', 'iso_alpha_3' => 'TTO'],
            ['name' => 'Tunisia', 'iso_alpha_2' => 'TN', 'iso_alpha_3' => 'TUN'],
            ['name' => 'Turkey', 'iso_alpha_2' => 'TR', 'iso_alpha_3' => 'TUR'],
            ['name' => 'Turkmenistan', 'iso_alpha_2' => 'TM', 'iso_alpha_3' => 'TKM'],
            ['name' => 'Turks and Caicos Islands', 'iso_alpha_2' => 'TC', 'iso_alpha_3' => 'TCA'],
            ['name' => 'Tuvalu', 'iso_alpha_2' => 'TV', 'iso_alpha_3' => 'TUV'],
            ['name' => 'Uganda', 'iso_alpha_2' => 'UG', 'iso_alpha_3' => 'UGA'],
            ['name' => 'Ukraine', 'iso_alpha_2' => 'UA', 'iso_alpha_3' => 'UKR'],
            ['name' => 'United Arab Emirates', 'iso_alpha_2' => 'AE', 'iso_alpha_3' => 'ARE'],
            ['name' => 'United Kingdom', 'iso_alpha_2' => 'GB', 'iso_alpha_3' => 'GBR'],
            ['name' => 'United States', 'iso_alpha_2' => 'US', 'iso_alpha_3' => 'USA'],
            ['name' => 'United States Minor Outlying Islands', 'iso_alpha_2' => 'UM', 'iso_alpha_3' => 'UMI'],
            ['name' => 'Uruguay', 'iso_alpha_2' => 'UY', 'iso_alpha_3' => 'URY'],
            ['name' => 'Uzbekistan', 'iso_alpha_2' => 'UZ', 'iso_alpha_3' => 'UZB'],
            ['name' => 'Vanuatu', 'iso_alpha_2' => 'VU', 'iso_alpha_3' => 'VUT'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'iso_alpha_2' => 'VE', 'iso_alpha_3' => 'VEN'],
            ['name' => 'Viet Nam', 'iso_alpha_2' => 'VN', 'iso_alpha_3' => 'VNM'],
            ['name' => 'Virgin Islands, British', 'iso_alpha_2' => 'VG', 'iso_alpha_3' => 'VGB'],
            ['name' => 'Virgin Islands, U.S.', 'iso_alpha_2' => 'VI', 'iso_alpha_3' => 'VIR'],
            ['name' => 'Wallis and Futuna', 'iso_alpha_2' => 'WF', 'iso_alpha_3' => 'WLF'],
            ['name' => 'Western Sahara', 'iso_alpha_2' => 'EH', 'iso_alpha_3' => 'ESH'],
            ['name' => 'Yemen', 'iso_alpha_2' => 'YE', 'iso_alpha_3' => 'YEM'],
            ['name' => 'Zambia', 'iso_alpha_2' => 'ZM', 'iso_alpha_3' => 'ZMB'],
            ['name' => 'Zimbabwe', 'iso_alpha_2' => 'ZW', 'iso_alpha_3' => 'ZWE'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert($country);
        }
    }
}
